version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: devcomply_db
    restart: always
    environment:
      POSTGRES_USER: devcomply_user
      POSTGRES_PASSWORD: Direto00@
      POSTGRES_DB: devcomply_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: